### ISSUE TITLE
Where do I keep the test scripts?

### ISSUE THREAD

**Issue by lockywolf** [mhagger/git-test#10]
I am sorry, this is more of a question than a bug, buy may be also considered as a documentation improvement suggestion.

Say, I have a git repository with many branches. None of this branches has a 'test' directory. What I want is to check if all the branches pass (or fail) a certain set of tests. (Essentially, several of my slaves are competing for the best implementation of a certain feature), and I am developing tests to choose the winner. Those tests are continuously improved, so I can't just add+commit them to every branch.

What's the best practice in this case?

ShaII I just add a test like this?:

`git test add ../testproject/test.sh`
 
Or shall I keep a .gitignored directory hardlink to a test project?

**Comment by mhagger** [comment]
The test can be an arbitrary command, so it would be fine to do `git test add ../testproject/test.sh` (or pretty much anything else that's convenient).

Be aware that when you change your test script, old test results stored by `git-test` might become invalid. So you might need to use `git test forget-results` once in a while to forget results from old versions of the tests.
